name: bankapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Database
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/

  # Custom fonts
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100

    - family: OverpassMono
      fonts:
        - asset: assets/fonts/OverpassMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/OverpassMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OverpassMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/OverpassMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/OverpassMono-Light.ttf
          weight: 300

    - family: Playfair
      fonts:
        # Regular
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        # Italic
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic