name: bankapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Database
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1

  # UI
  animate_gradient: ^0.0.3
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  rive: ^0.13.20
  flex_color_picker: ^3.7.1

  # Icons Packs
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  fluentui_system_icons: ^1.1.273
  phosphor_flutter: ^2.1.0
  lucide_icons_flutter: ^3.1.0
  health_icons: ^0.0.2
  tdesign_flutter: ^0.2.5
  solar_icons: ^0.0.5
  flutter_material_design_icons: ^1.1.7447

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  translator: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.5.4
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/icons/system/
    - assets/animations/gif/
    - .env
  # Custom fonts
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100

    - family: OverpassMono
      fonts:
        - asset: assets/fonts/OverpassMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/OverpassMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OverpassMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/OverpassMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/OverpassMono-Light.ttf
          weight: 300

    - family: Playfair
      fonts:
        # Regular
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        # Italic
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic

    - family: Roboto
      fonts:
        # Regular
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        # Italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100