// Mocks generated by Mockito 5.4.6 from annotations
// in bankapp/test/presentation/viewmodels/features/transaction_edit_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bankapp/domain/entities/entities.dart' as _i2;
import 'package:bankapp/domain/repositories/transaction_repository.dart' as _i3;
import 'package:bankapp/domain/value_objects/value_objects.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i3.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Transaction>> getAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, []),
            returnValue: _i4.Future<List<_i2.Transaction>>.value(
              <_i2.Transaction>[],
            ),
          )
          as _i4.Future<List<_i2.Transaction>>);

  @override
  _i4.Future<List<_i2.Transaction>> getTransactionsByAccountId(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByAccountId, [accountId]),
            returnValue: _i4.Future<List<_i2.Transaction>>.value(
              <_i2.Transaction>[],
            ),
          )
          as _i4.Future<List<_i2.Transaction>>);

  @override
  _i4.Future<_i2.Transaction?> getTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i4.Future<_i2.Transaction?>.value(),
          )
          as _i4.Future<_i2.Transaction?>);

  @override
  _i4.Future<_i2.Transaction> createTransaction(_i2.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i4.Future<_i2.Transaction>.value(
              _FakeTransaction_0(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i4.Future<_i2.Transaction>);

  @override
  _i4.Future<_i2.Transaction> updateTransaction(_i2.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i4.Future<_i2.Transaction>.value(
              _FakeTransaction_0(
                this,
                Invocation.method(#updateTransaction, [transaction]),
              ),
            ),
          )
          as _i4.Future<_i2.Transaction>);

  @override
  _i4.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> getTransactionsWithBalance(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsWithBalance, [accountId]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>>
  getTransactionsWithBalanceInRange(int? accountId, _i5.DateRange? dateRange) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsWithBalanceInRange, [
              accountId,
              dateRange,
            ]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> getTransactionsAroundToday(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsAroundToday, [accountId]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> searchTransactionsByKeyword(
    int? accountId,
    String? keyword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTransactionsByKeyword, [
              accountId,
              keyword,
            ]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> filterTransactionsByAmount(
    int? accountId,
    double? minAmount,
    double? maxAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterTransactionsByAmount, [
              accountId,
              minAmount,
              maxAmount,
            ]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> getTransactionsByCategory(
    int? accountId,
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCategory, [
              accountId,
              categoryId,
            ]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>> getTransactionsByCounterparty(
    int? accountId,
    int? counterpartyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCounterparty, [
              accountId,
              counterpartyId,
            ]),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Stream<List<_i2.Transaction>> watchAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTransactions, []),
            returnValue: _i4.Stream<List<_i2.Transaction>>.empty(),
          )
          as _i4.Stream<List<_i2.Transaction>>);

  @override
  _i4.Stream<List<_i2.Transaction>> watchTransactionsByAccountId(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactionsByAccountId, [accountId]),
            returnValue: _i4.Stream<List<_i2.Transaction>>.empty(),
          )
          as _i4.Stream<List<_i2.Transaction>>);

  @override
  _i4.Stream<List<_i2.TransactionWithBalance>> watchTransactionsWithBalance(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactionsWithBalance, [accountId]),
            returnValue: _i4.Stream<List<_i2.TransactionWithBalance>>.empty(),
          )
          as _i4.Stream<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<_i2.TransactionWithBalance>>
  getFollowedTransactionsWithDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getFollowedTransactionsWithDetails, []),
            returnValue: _i4.Future<List<_i2.TransactionWithBalance>>.value(
              <_i2.TransactionWithBalance>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionWithBalance>>);

  @override
  _i4.Future<List<int>> getFollowedTransactionIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFollowedTransactionIds, []),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<bool> isTransactionFollowed(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#isTransactionFollowed, [transactionId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> followTransaction(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#followTransaction, [transactionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowTransaction(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowTransaction, [transactionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTransactionStatus(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTransactionStatus, [transactionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
